//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DensNDente_Warehouse_Management.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductVendorLink
    {
        public int Id { get; set; }
        public int VendorId { get; set; }
        public int ProductId { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblVendor tblVendor { get; set; }
    }
}
